#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

__usage="
Usage: notes [--help | -h | -?] <command> [<args>]

Subcommands:
    new                Create a new note with your EDITOR
    list               List all found notes
    todos              List todo items from all of your notes
    find               Find notes with matching title
    search             Search notes for text

Options:
    -h, -?, --help     Output usage for notes or a subcommand
"

if [[ $# -lt 1 ]]; then
    echo "$__usage" >&2
    exit 1
fi

PARAMS=""
SUBCOMMAND=0

while (( "$#" )); do
    if [[ $SUBCOMMAND -eq 1 ]]; then
        PARAMS="$PARAMS $*"
        break
    fi
    case "$1" in
        -h|-'?'|--help)
            echo "$__usage"
            exit 0
            ;;
        --*=|-*) # unsupported options
            echo "Error: Unsupported option \"$1\"" >&2
            echo "$__usage" >&2
            exit 1
            ;;
        new|news|list|todos|find|search) # preserve positional arguments
            PARAMS="$PARAMS $1"
            shift
            SUBCOMMAND=1
            ;;
        *) # reject unsupported subcommands
            echo "Error: Unsupported command \"$1\"" >&2
            echo "$__usage" >&2
            exit 1
            ;;
    esac
done

# set positional arguments in their proper place
eval set -- "$PARAMS"

binary="notes-$1"

set +e
binary_path=$(which "$binary")
set -e

if [ -z "$binary_path" ]; then
    echo "Error: Binary \"$binary\" not found" >&2
    echo "$__usage" >&2
    exit 1
fi

shift

$binary_path "$*"
