name: reviewdog

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck-pr-review
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          pattern: "*"
          exclude: ".*\\.*"
      - name: shellcheck-pr-check
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          pattern: "*"
          exclude: ".*\\.*"

